on: [push, pull_request]

name: CI test and lint

jobs:
  check_test:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check --workspace

      - name: Run cargo check no features
        run: cargo check --workspace --no-default-features --features "audioadapter/libm, audioadapter-sample/libm, audioadapter-buffers/libm"

      - name: Run cargo test
        run: cargo test --workspace

      - name: Run cargo no-default-features tests
        run: cargo test --workspace --no-default-features --features "audioadapter/libm, audioadapter-sample/libm, audioadapter-buffers/libm"

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
