on:
  push:
    tags:
      - '*'

name: Publish on crates.io

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Publish audioadapter crate
        # Adding a default "std" feature to this crate would be a breaking change,
        # so instead just enable the libm feature when performing the compile test.
        run: cargo publish -p audioadapter --features "libm" --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish sample crate
        run: cargo publish -p audioadapter-sample --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish buffers crate
        run: cargo publish -p audioadapter-buffers --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}



